### ISSUE TITLE
Detect Syncthing-Android running

### ISSUE THREAD

**Issue by licaon-kter** [Nutomic/syncthing-lite#18]
...and inform the user that [both apps can't run at the same time](https://github.com/Nutomic/syncthing-lite/issues/6#issuecomment-354061604)

/PS: Why can't they run?

**Comment by Nutomic** [comment]
Syncthing Lite only has a partial implementation of the local discovery protocol. If the local discovery listen port is taken, it will not be able to connect to other devices over local discovery. Global discovery and relays will still work.

The new version has a warning dialog in this case.
