### ISSUE TITLE
app crashes almost unconditionally

### ISSUE THREAD

**Issue by mi5o** [Nutomic/syncthing-lite#24]
I was just trying whether syncthing-lite will be better option for me than full syncthing. I did not succeed making it work.

As soon as I add a device and I select "update remote index" from the menu, the application immediately force-closes. Sometimes it crashes just few seconds after starting without me doing anything.

Client:
  - Syncthing Lite 0.1.5 from F-Droid
  - CyanogenMon 12.1 (Android 5.1.1), Linux kernel 3.4.109

Server:
  - Syncthing Lite 0.14.43 from Syncthing repository for Debian x64

Logcat selection:
```
E/AndroidRuntime( 7097): FATAL EXCEPTION: Thread-3264
E/AndroidRuntime( 7097): Process: net.syncthing.lite, PID: 7097
E/AndroidRuntime( 7097): java.lang.IllegalArgumentException: /storage/emulated/0/Android/data/net.syncthing.lite/cache does not exist
E/AndroidRuntime( 7097): 	at org.apache.commons.io.FileUtils.checkDirectory(FileUtils.java:2692)
E/AndroidRuntime( 7097): 	at org.apache.commons.io.FileUtils.sizeOfDirectory(FileUtils.java:2579)
E/AndroidRuntime( 7097): 	at net.syncthing.java.core.cache.FileBlockCache.<init>(FileBlockCache.kt:31)
E/AndroidRuntime( 7097): 	at net.syncthing.java.core.cache.BlockCache$Companion.getBlockCache(BlockCache.kt:40)
E/AndroidRuntime( 7097): 	at net.syncthing.java.bep.BlockPuller.<init>(BlockPuller.kt:35)
E/AndroidRuntime( 7097): 	at net.syncthing.java.bep.BlockExchangeConnectionHandler.<init>(BlockExchangeConnectionHandler.kt:64)
E/AndroidRuntime( 7097): 	at net.syncthing.java.client.SyncthingClient.openConnection(SyncthingClient.kt:64)
E/AndroidRuntime( 7097): 	at net.syncthing.java.client.SyncthingClient.getDeviceConnection(SyncthingClient.kt:86)
E/AndroidRuntime( 7097): 	at net.syncthing.java.client.SyncthingClient.access$getDeviceConnection(SyncthingClient.kt:38)
E/AndroidRuntime( 7097): 	at net.syncthing.java.client.SyncthingClient$getPeerConnections$1.run(SyncthingClient.kt:117)
E/AndroidRuntime( 7097): 	at java.lang.Thread.run(Thread.java:818)
W/ActivityManager(  704):   Force finishing activity 1 net.syncthing.lite/.activities.MainActivity
```

It seems the application crashes on non-existence of `/storage/emulated/0/Android/data/net.syncthing.lite/cache`, which indeed does not exist on my device. The closest matches are:

- `/mnt/shell/emulated/0/Android/data/net.syncthing.lite/cache/`
- `/storage/emulated/legacy/Android/data/net.syncthing.lite/cache/`
- `/storage/sdcard0/Android/data/net.syncthing.lite/cache/`

where the latter two are just symlinks to the first one.

**Comment by Nutomic** [comment]
Pretty sure this was just missing a call to `mkdirs`. Should be fixed for the next version.
