### ISSUE TITLE
Removing known device device does not work

### ISSUE THREAD

**Issue by joaofl** [Nutomic/syncthing-lite#29]
I have two devices which I couldnt get connected at all, which I was trying to remove and add again. But it happens that one can not remove any device added.

**Comment by Nutomic** [comment]
Which app version are you using?

**Comment by joaofl** [comment]
I believe it is version 2.0. It happens to the latest one found in F-Droid and Google Play.

It is important to notice that apart from this issue, I could not add the devices I tried, so maybe it happens that one can not delete devices which are still not "paired".

Another observation: when you ask the version of the app, its hard to really know it, since there is nowhere in the app one can see the version in use. I make sense to have it there somewhere.

**Comment by Nutomic** [comment]
If you got the app from F-Droid, it is currently not up to date (will be fixed with the next version). I will add a screen in the app to show the version.

**Comment by Nutomic** [comment]
Fixed release is out.
