### ISSUE TITLE
Error Building..

### ISSUE THREAD

**Issue by jdevora** [Nutomic/syncthing-lite#4]
I'm trying to build the project, what is the recommended environment?
 
I'm trying to build it in an Ubuntu environment inside WLS (Ubuntu for Windows ) and get an error downloading the Android Tools
```
* What went wrong:
A problem occurred configuring root project 'syncthing-lite'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve com.android.tools.build:gradle:3.0.1.
     Required by:
         project :
      > Could not resolve com.android.tools.build:gradle:3.0.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.0.1/gradle-3.0.1.pom'.
               > sun.security.validator.ValidatorException: No trusted certificate found

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by Nutomic** [comment]
You need the Android SDK to build. The easiest option is to install Android Studio and just import the project. You also have to install [the backend library](https://github.com/Nutomic/a-sync) from source, using `./gradlew install`. All of this should work with the normal windows console.

I will add these instructions to the readme.
