### ISSUE TITLE
Request storage permission to avoid crash

### ISSUE THREAD

**Issue by ImPat** [Nutomic/syncthing-lite#7]
On android 6.0 and above devices need to request storage access to get access to the file system. Unfortunately, syncthing-lite crashes without access to the file system. Requesting access to the file system at every start of the app should fix this issue.

**Comment by Nutomic** [comment]
It already does request that permission whenever you download or upload a file. Can you describe how I can reproduce this crash?

**Comment by ImPat** [comment]
Turns out I can't reproduce it myself. I probably changed the orientation of my phone. This will cause a crash regardless of storage permission.
Steps to reproduce: 
-Launch app
-Change the orientation of device
-Crash
Tested on: Touchwiz Android 7.0 and Touchwiz Android 6.0.1

**Comment by Nutomic** [comment]
Oh thats right.
